ncpus: 1
mem: 10GB
#walltime: 07:00:00
walltime: 00:10:00
#walltime: 00:10:00
jobname: CChannel
project: v45
queue: express

model: mitgcm
shortpath: /short/v45
exe: mitgcmuv
input: channel_input

collate: False

#mpi:
#     module: openmpi/1.6.3
#    module: netcdf/4.4.1.1
#mpiP: True
#ipm: 2.0.2
#itac: 9.0.3.051

#mpirun: -trace
